<?php

use MailPoetVendor\Twig\Environment;
use MailPoetVendor\Twig\Error\LoaderError;
use MailPoetVendor\Twig\Error\RuntimeError;
use MailPoetVendor\Twig\Extension\SandboxExtension;
use MailPoetVendor\Twig\Markup;
use MailPoetVendor\Twig\Sandbox\SecurityError;
use MailPoetVendor\Twig\Sandbox\SecurityNotAllowedTagError;
use MailPoetVendor\Twig\Sandbox\SecurityNotAllowedFilterError;
use MailPoetVendor\Twig\Sandbox\SecurityNotAllowedFunctionError;
use MailPoetVendor\Twig\Source;
use MailPoetVendor\Twig\Template;

/* newsletters/campaign_stats.html */
class __TwigTemplate_027c265ea8e198fafbdee6acace9c0afe0e82b7802c6e1e9dc612d57d158c310 extends \MailPoetVendor\Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 1
        echo "<script type=\"text/javascript\">
  var mailpoet_shortcode_links = ";
        // line 2
        echo json_encode(($context["shortcode_links"] ?? null));
        echo ";
</script>

";
        // line 5
        echo $this->extensions['MailPoet\Twig\I18n']->localize(["revenueStatsTooltip" => $this->extensions['MailPoet\Twig\I18n']->translate("Revenues generated by customers who made a purchase within two weeks after they clicked on this email. This is the sum of the order totals including shipping and taxes."), "revenuesStats" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("%1s from %2s orders", "For example: \"£451 from 3 orders\""), "productsSold" => $this->extensions['MailPoet\Twig\I18n']->translate("Products Sold"), "nProductsSold" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("%1s products sold", "For example: \"5 products sold\""), "totalNetRevenue" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Total net revenue %1s", "For example: \"Total net revenue £25.32\""), "noClickedLinksFound" => $this->extensions['MailPoet\Twig\I18n']->translate("No clicked links found"), "linkColumn" => $this->extensions['MailPoet\Twig\I18n']->translate("Link"), "uniqueClicksColumn" => $this->extensions['MailPoet\Twig\I18n']->translate("Unique clicks"), "loadingEngagementItems" => $this->extensions['MailPoet\Twig\I18n']->translate("Loading data..."), "noEngagementItemsFound" => $this->extensions['MailPoet\Twig\I18n']->translate("No engagement data found"), "subscriberColumn" => $this->extensions['MailPoet\Twig\I18n']->translate("Subscriber"), "statusColumn" => $this->extensions['MailPoet\Twig\I18n']->translate("Status"), "dateAndTimeColumn" => $this->extensions['MailPoet\Twig\I18n']->translate("Date and time"), "opened" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Opened", "Subscriber engagement status - subscriber opened a newsletter"), "clicked" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Clicked", "Subscriber engagement status - subscriber clicked a newsletter link"), "unsubscribed" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Unsubscribed", "Subscriber engagement status - subscriber unsubscribed from a newsletter"), "unopened" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Unopened", "Subscriber engagement status - subscriber did not open a newsletter"), "createSegment" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Create Segment", "Button label on Subscriber engagement page"), "savingSegment" => $this->extensions['MailPoet\Twig\I18n']->translate("Saving..."), "successMessage" => $this->extensions['MailPoet\Twig\I18n']->translate("Segment \"%s\" created. [link]Create and send an email to it.[/link]"), "segmentExists" => $this->extensions['MailPoet\Twig\I18n']->translate("Segment already exists."), "deletedSubscriber" => $this->extensions['MailPoet\Twig\I18n']->translateWithContext("Deleted subscriber", "A fallback for an email of a deleted subscriber")]);
        // line 28
        echo "
";
    }

    public function getTemplateName()
    {
        return "newsletters/campaign_stats.html";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  48 => 28,  46 => 5,  40 => 2,  37 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("", "newsletters/campaign_stats.html", "/home/u20s1035/dev_root/wp-content/plugins/mailpoet-premium/views/newsletters/campaign_stats.html");
    }
}
